# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfjson2hcl" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "7c95851fcb787c27880789579c9b72fa2e9c1f213a80b8692dbda6a1cbf623a0"
      url "https://github.com/winebarrel/tfjson2hcl/releases/download/v#{version}/tfjson2hcl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2527c04f798fa595af9129c7176aa7fd1918f8e10bff44ee87fcfb7e439783c9"
      url "https://github.com/winebarrel/tfjson2hcl/releases/download/v#{version}/tfjson2hcl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "04efbe862e22dd94c34c24204c98b662ce4ad03d031cd1f05f74127f41087549"
      url "https://github.com/winebarrel/tfjson2hcl/releases/download/v#{version}/tfjson2hcl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b579b5d2f1eb4027fcb865b08148ff7accb2a24b64b62a3467abd449cca60323"
      url "https://github.com/winebarrel/tfjson2hcl/releases/download/v#{version}/tfjson2hcl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tfjson2hcl"
  desc "tfjson2hcl converts heredoc JSON in Terraform files into jsonencode({...}) expressions."
  homepage "https://github.com/winebarrel/tfjson2hcl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfjson2hcl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfjson2hcl"]
    end
  end

  # No zap stanza required

end
